---

#USER AND DIRECTORY CONFIG
HADOOP_USER: root
HADOOP_GROUP: root
HADOOP_INSTALL_LOC: /usr/local
JAVA_INSTALL_LOC: /usr/local
HADOOP_MASTER: localhost
#Mention where to create hivedirectories on master node
HADOOP_HDFS_NAME_PREFIX: /data/dataa

#JAVA VERSION
JAVA_INSTALL_FILE: jdk-8u131-linux-x64.tar.gz
JAVA_FOLDER: jdk1.8.0_131

##HADOOP_VERSION
HADOOP_INSTALL_FILE: hadoop-2.8.1.tar.gz
HADOOP_FOLDER: hadoop-2.8.1

BENCHMARK_USER: "{{HADOOP_USER}}"
BIGBENCH_INSTALL_LOC: "/{{BENCHMARK_USER}}"

HIVE_REMOTE_SRC: no
SPARK_WITHOUTHIVE_SRC: no
SPARK_WITH_HIVE_SRC: no
DERBY_REMOTE_SRC: no


#Hive version 
HIVE_INSTALL_FILE: apache-hive-3.0.0-SNAPSHOT-bin.tar.gz
HIVE_FOLDER: apache-hive-3.0.0-SNAPSHOT-bin
HIVE_CUSTOM_BUILD: no
HIVE_VERSION_PREFIX: 3

#SPARK CUSTOM BUILD FOR HIVE ON SPARK
SPARK_WITHOUT_HIVE_INSTALL_FILE: spark-2.2.0-bin-hadoop27-without-hive.tgz
SPARK_WITHOUT_HIVE_FOLDER: spark-2.2.0-bin-hadoop28-without-hive

SPARK_WITH_HIVE_INSTALL_FILE: spark-2.2.0-bin-hadoop27_with_Phive.tgz
SPARK_WITH_HIVE_FOLDER: spark-2.2.0-bin-hadoop27_with_Phive

#DERBY VERSION
DERBY_INSTALL_FILE: db-derby-10.10.2.0-bin.zip
DERBY_FOLDER: db-derby-10.10.2.0-bin

#Downloaded BigBench tar file
BIGBENCH_FILE: TPCx-BB_v1.2.zip
BIGBENCH_FOLDER: TPCx-BB_v1.2
BIG_BENCH_ENGINE: hive

#SPARK EXECUTOR MEMORY SETTINGS
SPARK_DRIVER_MEM: 10g
SPARK_EXECUTOR_MEM: 26g
SPARK_EXECUTOR_CORES: 8
SPARK_YARN_EXECUTOR_MEM_OVERHEAD_MB: 4096
BIGBENCH_100TB_TUNINGS: "no"
BIGBENCH_USE_NR_HUGEPAGES: "yes"
REMOTE_BIGBENCH_SRC: no
